Description of GetObsModelFixedO
GetObsModelFixedO
PURPOSE
Defines p(o|s) for a fixed 'o'.
SYNOPSIS
function p=GetObsModelFixedO(OM,o)
DESCRIPTION
   Defines p(o|s) for a fixed 'o'.
   Instantiates the observation model for a particular observation 'o'.
   The CS_CO_ObsModel defines p(o,s) via Kernel smoothing: using a double
   Gaussian on 's' and on 'o'. From here:
       p(o|s)=p(o,s)/p(s)
   Where we assume p(s) as uniform.
   The output is not normalized.
   See also CS_CO_ObsModel
CROSS-REFERENCE INFORMATION
This function calls:
GMixture Gaussian mixture constructor.
Value Evaluates a GMixture.
Value Evaluation of a Gaussian.
UniformProbability Uniform probability value on a continuous space.
UniformProbability Uniform probability value on a discrete space.
This function is called by:
MakeFigure1 Generates Figure 1.
DiscretizeObsModel Discretizes the observation model on the observation side.
Update Belief evolution under an observation model.
ComputeAlpha_j_a_o Computes a particular alpha-element.
ComputeAlpha_j_a_o Computes a particular alpha-element.
SOURCE CODE
function p=GetObsModelFixedO(OM,o)
%   Defines p(o|s) for a fixed 'o'.
%
%   Instantiates the observation model for a particular observation 'o'.
%   The CS_CO_ObsModel defines p(o,s) via Kernel smoothing: using a double
%   Gaussian on 's' and on 'o'. From here:
%       p(o|s)=p(o,s)/p(s)
%   Where we assume p(s) as uniform.
%
%   The output is not normalized.
%
%   See also CS_CO_ObsModel
  w=OM.w.*cellfun(@(x)(Value(x,o)),OM.gO);
  ps=UniformProbability(OM.S);
  p=GMixture(w,OM.gS)/ps;