Description of dim
dim
PURPOSE
Dimensionality of a discrete space.
SYNOPSIS
function d=dim(DS)
DESCRIPTION
   Dimensionality of a discrete space.
   Returns the number of dimensions of the discrete space 'DS'.
   See also DSpace.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
DiscretizeActionModel Generates a new action model discretizing the action space.
CS_DA_ActionModel CS_DA_ActionModel constructor.
DiscretizeActionModel Produces a new action model discretizing the state space.
DS_CA_ActionModel DS_CA_ActionModel constructor.
DS_DA_ActionModel DS_DA_ActionModel constructor.
GetTest1caParameters The example on Figure 10.
rand Generates random points on a GMixture.
DiscretizeObsModel Discretizes the observation model on the observation side.
plot Plots the CS_CO_ObsModel
CS_DO_ObsModel CS_DO_ObsModel constructor.
DiscretizeObsModel Discretizes the observation model on the state side.
DS_CO_ObsModel DS_CO_ObsModel constructor.
DS_DO_ObsModel DS_DO_ObsModel constructor.
ComputeAlpha_a Compute the alpha_i_n-element for the given action and belief.
Backup Backup for a given belief (continuous state version).
ComputeAlpha_a Compute the alpha_i_n-element for the given action and belief.
Backup Backupt for a given belief (discrete state version).
ComputeAlpha_j_a_o Computes a particular alpha-element.
ComputeAlphas_j_a_o Computes the set of al possible alpha-elements.
DiscretizeRewardModel Discretizes the reward model on the action side.
plot Plots the CS_CA_RewardModel
CS_DA_RewardModel CS_DA_RewardModel constructor.
DiscretizeRewardModel Discretizes the reward model on the state side.
DS_CA_RewardModel DS_CA_RewardModel constructor.
DS_DA_RewardModel DS_DA_RewardModel constructor.
SOURCE CODE
function d=dim(DS)
%   Dimensionality of a discrete space.
%
%   Returns the number of dimensions of the discrete space 'DS'.
%
%   See also DSpace.
  d=DS.max;