Description of RandVector
RandVector
PURPOSE
Selects and element from a discrete probability distribution.
SYNOPSIS
function i=RandVector(v)
DESCRIPTION
   Selects and element from a discrete probability distribution.
   Returns an element at random using the (absolute) values of the input
   vector as selection weights.
CROSS-REFERENCE INFORMATION
This function calls:
rand Random state from a discrete belief.
rand Random state from a belief.
rand Generates random points on a GMixture.
rand Generates random ponts on a Gaussian.
rand Random state from a continuous space.
rand Random state from a discrete space.
This function is called by:
Prediction Belief evolution under the given action.
Prediction Belief evolution under the given action.
rand Random state from a discrete belief.
Update Belief evolution under an observation model.
rand Random state from a belief.
rand Generates random points on a GMixture.
SimulationStep Executes one step of a POMDP simulation.
SOURCE CODE
function i=RandVector(v)
%   Selects and element from a discrete probability distribution.
%
%   Returns an element at random using the (absolute) values of the input
%   vector as selection weights.
  va=abs(v);
  r=rand*sum(va);
  i=1;
  s=va(i);
  while s<r
    i=i+1;
    s=s+va(i);
  end