Description of display
display
PURPOSE
Displays belief information.
SYNOPSIS
function display(b)
DESCRIPTION
   Displays belief information.
   Displays the belief on discrete state space.
CROSS-REFERENCE INFORMATION
This function calls:
display Displays belief information.
display Displays Gaussian information.
This function is called by:
display Displays belief information.
display Displays Gaussian information.
SOURCE CODE
function display(b)
%   Displays belief information.
%
%   Displays the belief on discrete state space.
  display(b.v);