Description of Expectation
Expectation
PURPOSE
Expectation between a belief and a alpha-element.
SYNOPSIS
function e=Expectation(b,a)
DESCRIPTION
   Expectation between a belief and a alpha-element.
   Expectation operator for a belief 'b' on discrete state space and a given
   alpha element 'a' (alpha vector in this case).
   This is the basic operator on which the backup relies on and,
   consequently on which the whole planeer is based on.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
Values Belief value with all alpha-elements in the Policy.
ComputeAlpha_a Compute the alpha_i_n-element for the given action and belief.
Backup Backup for a given belief (continuous state version).
ComputeAlpha_a Compute the alpha_i_n-element for the given action and belief.
Backup Backupt for a given belief (discrete state version).
Perseus The Perseus point-based POMDP solver.
iPerseus Improved version of Perseus.
SOURCE CODE
function e=Expectation(b,a)
%   Expectation between a belief and a alpha-element.
%
%   Expectation operator for a belief 'b' on discrete state space and a given
%   alpha element 'a' (alpha vector in this case).
%
%   This is the basic operator on which the backup relies on and,
%   consequently on which the whole planeer is based on.
  e=b.v'*a;