Description of ComputeAlpha_a
ComputeAlpha_a
PURPOSE
Compute the alpha_i_n-element for the given action and belief.
SYNOPSIS
function Element_a=ComputeAlpha_a(P,V,b,a,Alphas_j_a_o)
DESCRIPTION
   Compute the alpha_i_n-element for the given action and belief.
   Define the alpha-elements to be used in the backup (The \alpha_n^i
   elements).
   Particularly, this function defines those elements as described at the
   end of section 6.2 of the paper (see the last equation before
   Section 7).
   This function is only applied to POMDPs with discrete actions sets.
   Recall that continuous action sets are always discretized before
   entering the backup (See Table 2 in page 21). Thus, in practice the
   input 'P' is a DS_CO_DA_POMDP.
   Note that in this case the Alpha_j_a_o elements can not be pre-computed
   and that this parameter is given for compatibility with similar
   functions for other types of POMDP.
CROSS-REFERENCE INFORMATION
This function calls:
size Returns the size of a policy.
get Get for GBeliefs.
get Get function for the GMixture object.
get Gaussian object get function.
DiscretizeObsModel Discretizes the observation model on the observation side.
DiscretizeObsModel Discretizes the observation model on the state side.
DiscretizeObsModel Discretizes the observation model on the observation side.
DiscretizeObsModel Discretizes the observation model on the observation side.
get Get function for CS_CO_CA_POMDPs.
DiscretizeObsModel Discretizes the observation model on the observation side.
get Get function for CS_CO_DA_POMDPs.
get Get function for CS_CO_POMDPs.
get Get function for CS_DO_CA_POMDPs.
get Get function for CS_DO_DA_POMDPs.
ComputeAlpha_j_a_o Computes a particular alpha-element.
get Get function for CS_POMDPs.
DiscretizeObsModel Discretizes the observation model on the observation side.
get Get function for DS_CO_CA_POMDPs.
DiscretizeObsModel Discretizes the observation model on the observation side.
get Get function for DS_CO_DA_POMDPs.
get Get function for DS_DO_CA_POMDPs.
get Get function for DS_DO_DA_POMDPs.
ComputeAlpha_j_a_o Computes a particular alpha-element.
DiscretizeObsModel Discretizes a POMDP on the observation side.
get Get functio for POMDPs.
GetRewardModelFixedA Defines the reward function for a given action.
GetRewardModelFixedA Defines the reward function for a given action.
GetRewardModelFixedA Defines the reward function for a given action.
GetRewardModelFixedA Defines the reward function for a given action.
This function is called by:
Backup Backup for a given belief (continuous state version).
Backup Backupt for a given belief (discrete state version).
SOURCE CODE
function Element_a=ComputeAlpha_a(P,V,b,a,Alphas_j_a_o)
%   Compute the alpha_i_n-element for the given action and belief.
%
%   Define the alpha-elements to be used in the backup (The \alpha_n^i
%   elements).
%   Particularly, this function defines those elements as described at the
%   end of section 6.2 of the paper (see the last equation before
%   Section 7).
%
%   This function is only applied to POMDPs with discrete actions sets.
%   Recall that continuous action sets are always discretized before
%   entering the backup (See Table 2 in page 21). Thus, in practice the
%   input 'P' is a DS_CO_DA_POMDP.
%
%   Note that in this case the Alpha_j_a_o elements can not be pre-computed
%   and that this parameter is given for compatibility with similar
%   functions for other types of POMDP.
  P1=DiscretizeObsModel(P,V,b,a); % This returns a CS_DO_DA_POMDP
  nj=size(V);
  gamma=get(P,'gamma');
  Element_a=ComputeAlpha_j_a_o(P1,V,1,a,1);
  for j=2:nj
    Element_a=Element_a+ComputeAlpha_j_a_o(P1,V,j,a,j);
  end
  Element_a=GetRewardModelFixedA(P,a)+gamma*Element_a;