Description of GBelief
GBelief
PURPOSE
Gaussian-based belief constructor.
SYNOPSIS
function gb=GBelief(varargin)
DESCRIPTION
   Gaussian-based belief constructor.
   Generates a belief on a continuous state space using a gaussian
   mixture.
   Parameters:
      GM: The Gaussian mixture.
      maxC: The maximum number of components in the mixtures representing
            beliefs. Beliefs with larger mixtures are compressed to fit in
            this threshold.
   Note that GBelief inherits from Belief but also from GMixture. Thus,
   all GMixture functions are directly appliable to GBeliefs.
CROSS-REFERENCE INFORMATION
This function calls:
Belief Belief constructor.
GBelief Gaussian-based belief constructor.
Compress Gaussian mixutre compression.
Normalize Normalize a GMixture.
This function is called by:
GBelief Gaussian-based belief constructor.
Prediction Belief evolution given a transition model.
Update Belief evolution under an observation model.
GetTest1Parameters The example on Figure 1.
MakeFigure4 Generates Figure 4.
SOURCE CODE
function gb=GBelief(varargin)
%   Gaussian-based belief constructor.
%
%   Generates a belief on a continuous state space using a gaussian
%   mixture.
%   Parameters:
%      GM: The Gaussian mixture.
%      maxC: The maximum number of components in the mixtures representing
%            beliefs. Beliefs with larger mixtures are compressed to fit in
%            this threshold.
%
%   Note that GBelief inherits from Belief but also from GMixture. Thus,
%   all GMixture functions are directly appliable to GBeliefs.
  switch nargin
    case 1
      if isa(varargin{1},'GBelief')
        gb=varargin{1};
      else
        if isa(varargin{1},'GMixture')
          gb=GBelief(varargin{1},0);
        else
          error('Wrong parameter type in GBelief constructor');
        end
      end
    case 2
      if isa(varargin{1},'GMixture') && isa(varargin{2},'double')
        gb.maxC=floor(varargin{2});
        gm=Normalize(Compress(varargin{1},gb.maxC));
        b=Belief();
        gb=class(gb,'GBelief',b,gm);
      else
        error('Wrong parameter type in GBelief constructor');
      end
    otherwise
      error('Wrong number of parameters in GBelief constructor');
  end