Description of DiscretizeRewardModel
DiscretizeRewardModel
PURPOSE
Discretizes the reward model on the action side.
SYNOPSIS
function DRM=DiscretizeRewardModel(RM,A)
DESCRIPTION
   Discretizes the reward model on the action side.
   Defines a reward function on continuous states and discrete actions
   from a reward function on continuous states and actions.
   The provided set of 'samples' in the action space is used as the set of
   actions in the discrete set to be defined.
   Parameters:
     RM: The continous state/action action model to be discretized.
     A: The discrete set of actions to use in the discretization.
   See also CS_DA_RewardModel.
CROSS-REFERENCE INFORMATION
This function calls:
GMixture Gaussian mixture constructor.
Value Evaluates a GMixture.
Value Evaluation of a Gaussian.
CS_DA_RewardModel CS_DA_RewardModel constructor.
dim Dimensionality of a continuous space.
dim Dimensionality of a discrete space.
This function is called by:
DiscretizeActionModel Discretizes the action space CS_CO_CA_POMDP.
DiscretizeActionModel Discretizes the action space CS_DO_CA_POMDP.
Discretize Discretizes the state space of the CS_DO_DA_POMDP.
DiscretizeActionModel Discretizes the action space DS_DO_CA_POMDP.
SOURCE CODE
function DRM=DiscretizeRewardModel(RM,A)
%   Discretizes the reward model on the action side.
%
%   Defines a reward function on continuous states and discrete actions
%   from a reward function on continuous states and actions.
%   The provided set of 'samples' in the action space is used as the set of
%   actions in the discrete set to be defined.
%
%   Parameters:
%     RM: The continous state/action action model to be discretized.
%     A: The discrete set of actions to use in the discretization.
%
%   See also CS_DA_RewardModel.
  na=dim(A);
  r=cell(1,na);
  for i=1:na
    r{i}=GMixture(RM.w.*cellfun(@(ga)(Value(ga,A(i))),RM.gA),RM.gS);
  end
  DRM=CS_DA_RewardModel(RM.S,A,r);