Description of MaxAlpha
MaxAlpha
PURPOSE
Returns the maximizing alpha-element for a belief.
SYNOPSIS
function [nAlpha v]=MaxAlpha(P,b)
DESCRIPTION
   Returns the maximizing alpha-element for a belief.
   Returns the identifier of the Policy element maximizing the value for a
   given belief, b.
   Additionally, it returns the actual value for the given belief.
   See also Policy.
CROSS-REFERENCE INFORMATION
This function calls:
Values Belief value with all alpha-elements in the Policy.
max Upper bound of a CSpace
This function is called by:
GetPOMDPSolutionStatistics Collects statistics with the outcome of an experiment.
Perseus The Perseus point-based POMDP solver.
iPerseus Improved version of Perseus.
SOURCE CODE
function [nAlpha v]=MaxAlpha(P,b)
%   Returns the maximizing alpha-element for a belief.
%
%   Returns the identifier of the Policy element maximizing the value for a
%   given belief, b.
%   Additionally, it returns the actual value for the given belief.
%
%   See also Policy.
  [v nAlpha]=max(Values(P,b));