Description of OptimalAction
OptimalAction
PURPOSE
Returns the optimal action for a given belief.
SYNOPSIS
function [a v]=OptimalAction(P,b)
DESCRIPTION
   Returns the optimal action for a given belief.
   Returns the action associated with the element that maximizes the Policy
   value for a given belief.
   Additionally it also returns the maximazing value for the belief.
   See also Policy.
CROSS-REFERENCE INFORMATION
This function calls:
Values Belief value with all alpha-elements in the Policy.
max Upper bound of a CSpace
This function is called by:
MakeFigure3 Generates Figure 3.
MakeFigure4 Generates Figure 4.
SimulateFrom Simulates a POMDP from a given belief.
SOURCE CODE
function [a v]=OptimalAction(P,b)
%   Returns the optimal action for a given belief.
%
%   Returns the action associated with the element that maximizes the Policy
%   value for a given belief.
%   Additionally it also returns the maximazing value for the belief.
%
%   See also Policy.
  [v nAlpha]=max(Values(P,b));
  a=P.actions{nAlpha};