Description of size
size
PURPOSE
Returns the size of a policy.
SYNOPSIS
function s=size(P)
DESCRIPTION
   Returns the size of a policy.
   Returns the number of alpha elements in a given Policy object.
   See also Policy.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
CS_DA_ActionModel CS_DA_ActionModel constructor.
DS_CA_ActionModel DS_CA_ActionModel constructor.
DiscretizeActionModel Generates a new action model discretizing the action space of the given model.
DS_DA_ActionModel DS_DA_ActionModel constructor.
DBelief Discrete belief constructor.
PBelief Particle-based belief constructor.
plot Displays a particle-based belief.
GenerateFigure5Data Generates the data for Figure 5.
GenerateFigure7aData Generates the data for Figure 7-left.
MakeFigure4 Generates Figure 4.
GMixture Gaussian mixture constructor.
set Set method for Gaussian mixtures.
Gaussian Gaussian construtor.
Product Product of two Gaussians.
Value Evaluation of a Gaussian.
get Gaussian object get function.
GetPOMDPAverageStatistics Averages statistics collected after an experiment.
GetPOMDPSolutionStatistics Collects statistics with the outcome of an experiment.
ReadDiscretePOMDPData Reads a discrete POMDP from a file.
DiscretizeObsModel Discretizes the observation model on the observation side.
plot Plots the CS_CO_ObsModel
CS_DO_ObsModel CS_DO_ObsModel constructor.
DS_CO_ObsModel DS_CO_ObsModel constructor.
DiscretizeObsModel Discretizes the observation model on the observation side.
DS_DO_ObsModel DS_DO_ObsModel constructor.
DiscretizeObsModel Discretizes the observation model on the observation side.
ComputeAlpha_a Compute the alpha_i_n-element for the given action and belief.
ComputeAlpha_a Compute the alpha_i_n-element for the given action and belief.
ComputeAlpha_a Compute the alpha_i_n-element for the given action and belief.
ComputeAlphas_j_a_o Computes the set of al possible alpha-elements.
Perseus The Perseus point-based POMDP solver.
iPerseus Improved version of Perseus.
plot Plots the CS_CA_RewardModel
CS_DA_RewardModel CS_DA_RewardModel constructor.
DS_CA_RewardModel DS_CA_RewardModel constructor.
DS_DA_RewardModel DS_DA_RewardModel constructor.
CSpace CSpace constructor.
Discretize Converts a continuous space into a discrete one.
DSpace DSpace constructor.
SOURCE CODE
function s=size(P)
%   Returns the size of a policy.
%
%   Returns the number of alpha elements in a given Policy object.
%
%   See also Policy.
  s=P.n;