Description of Values
Values
PURPOSE
Belief value with all alpha-elements in the Policy.
SYNOPSIS
function v=Values(P,b)
DESCRIPTION
   Belief value with all alpha-elements in the Policy.
   Return the values of the given belief, b, for all the elements stored
   in the Policy, P.
   Recall that the optimal element for a belief is the one maximizing its
   value, i.e., the one maximizing the output of this function.
   See also MaxAlpha, OptimalAction.
CROSS-REFERENCE INFORMATION
This function calls:
Expectation Expectation between a belief and a alpha-element.
Expectation Expectation between a belief and a alpha-element.
Expectation Expectation between a belief and a alpha-element.
This function is called by:
MaxAlpha Returns the maximizing alpha-element for a belief.
OptimalAction Returns the optimal action for a given belief.
DiscretizeObsModel Discretizes the observation model on the observation side.
DiscretizeObsModel Discretizes the observation model on the observation side.
SOURCE CODE
function v=Values(P,b)
%   Belief value with all alpha-elements in the Policy.
%
%   Return the values of the given belief, b, for all the elements stored
%   in the Policy, P.
%   Recall that the optimal element for a belief is the one maximizing its
%   value, i.e., the one maximizing the output of this function.
%
%   See also MaxAlpha, OptimalAction.
  v=cellfun(@(e)(Expectation(b,e)),P.elements);