Description of Alpha0
Alpha0
PURPOSE
Alpha-element for the first Perseus iteration (discrete state version).
SYNOPSIS
function a=Alpha0(P)
DESCRIPTION
   Alpha-element for the first Perseus iteration (discrete state version).
   Generates the alpha element for initial planning horizion when working
   with discrete state spaces.
   The role of alpha_0 is detailed in Section 4, page 13, first paragraph.
CROSS-REFERENCE INFORMATION
This function calls:
get Get for GBeliefs.
get Get function for the GMixture object.
get Gaussian object get function.
get Get function for CS_CO_CA_POMDPs.
get Get function for CS_CO_DA_POMDPs.
get Get function for CS_CO_POMDPs.
get Get function for CS_DO_CA_POMDPs.
get Get function for CS_DO_DA_POMDPs.
get Get function for CS_POMDPs.
get Get function for DS_CO_CA_POMDPs.
get Get function for DS_CO_DA_POMDPs.
get Get function for DS_DO_CA_POMDPs.
get Get function for DS_DO_DA_POMDPs.
UniformDistribution Uniform distribution in the POMDP state space.
get Get functio for POMDPs.
minReward Lower bound of the minimal possible reward.
minReward Lower bound of the minimal possible reward.
minReward Lower bound of the minimal possible reward.
minReward Lower bound of the minimal possible reward.
UniformDistribution Uniform probability on a continuous space.
UniformDistribution Uniform probability on a discrete space.
This function is called by:
Perseus The Perseus point-based POMDP solver.
iPerseus Improved version of Perseus.
SOURCE CODE
function a=Alpha0(P)
%   Alpha-element for the first Perseus iteration (discrete state version).
%
%   Generates the alpha element for initial planning horizion when working
%   with discrete state spaces.
%   The role of alpha_0 is detailed in Section 4, page 13, first paragraph.
  S=get(P,'StateSpace');
  gamma=get(P,'gamma');
  [u v]=UniformDistribution(S);
  a=(minReward(P)/(1-gamma))*(1/v)*u;