Description of ComputeAlpha_j_a_o
ComputeAlpha_j_a_o
PURPOSE
Computes a particular alpha-element.
SYNOPSIS
function alpha_j_a_o=ComputeAlpha_j_a_o(P,V,j,a,o)
DESCRIPTION
   Computes a particular alpha-element.
   Computes a single alpha_j_a_o element as described in Section 3.1
   equation (6), but particularized for discrete state spaces.
   This function can be used when pre-computing the set of all alpha_j_a_o
   elements before the backup operation or when computing only one of
   them during the backup.
   Parameters
     P: The POMDP
     V: The previous policy/value function/set of alpha-elements.
     j: Index of the previous alpha element to use.
     a: Index of the action to use.
     o: Index of the observation to use.
CROSS-REFERENCE INFORMATION
This function calls:
GetActionModelFixedA Returns the action model for a given action.
GetActionModelFixedA Returns the action model for a given action.
GetActionModelFixedA Returns the action model for a given action.
GetActionModelFixedA Returns the action model for a given action.
get Get for GBeliefs.
get Get function for the GMixture object.
get Gaussian object get function.
GetObsModelFixedO Defines p(o|s) for a fixed 'o'.
GetObsModelFixedO Defines p(o|s) for a fixed 'o'.
GetObsModelFixedO Defines p(s|o).
GetObsModelFixedO Defines p(s|o).
get Get function for CS_CO_CA_POMDPs.
get Get function for CS_CO_DA_POMDPs.
get Get function for CS_CO_POMDPs.
get Get function for CS_DO_CA_POMDPs.
get Get function for CS_DO_DA_POMDPs.
get Get function for CS_POMDPs.
get Get function for DS_CO_CA_POMDPs.
get Get function for DS_CO_DA_POMDPs.
get Get function for DS_DO_CA_POMDPs.
get Get function for DS_DO_DA_POMDPs.
get Get functio for POMDPs.
dim Dimensionality of a continuous space.
dim Dimensionality of a discrete space.
This function is called by:
ComputeAlpha_a Compute the alpha_i_n-element for the given action and belief.
ComputeAlpha_a Compute the alpha_i_n-element for the given action and belief.
ComputeAlpha_a Compute the alpha_i_n-element for the given action and belief.
ComputeAlphas_j_a_o Computes the set of al possible alpha-elements.
SOURCE CODE
function alpha_j_a_o=ComputeAlpha_j_a_o(P,V,j,a,o)
%   Computes a particular alpha-element.
%
%   Computes a single alpha_j_a_o element as described in Section 3.1
%   equation (6), but particularized for discrete state spaces.
%
%   This function can be used when pre-computing the set of all alpha_j_a_o
%   elements before the backup operation or when computing only one of
%   them during the backup.
%
%   Parameters
%     P: The POMDP
%     V: The previous policy/value function/set of alpha-elements.
%     j: Index of the previous alpha element to use.
%     a: Index of the action to use.
%     o: Index of the observation to use.
  S=get(P,'StateSpace');
  ns=dim(S);
  p_s1_a_s=GetActionModelFixedA(P,a);
  p_o_s1=GetObsModelFixedO(P,o);
  alpha_j_a_o=full(sum(repmat(V{j}.*p_o_s1,1,ns).*p_s1_a_s,1)');