Description of Prediction
Prediction
PURPOSE
Belief evolution given a transition model.
SYNOPSIS
function bOut=Prediction(b,t,Sp)
DESCRIPTION
   Belief evolution given a transition model.
   Updates a particle-based belief with a given transiton probability function, 't'.
   Function 't' is the outcome of GetActionModelFixedA for the corresponding
   action model.
   Note that the prediction and update steps using particles are tied
   together (see Section 5.3.2 of the paper). However, for compatibility
   with the rest of belief representations it is nice to have separate
   Prediction and Update functions.
   Here we store a backup of the particles (to use them in the Update) and
   we randomly modify them using the action model.
CROSS-REFERENCE INFORMATION
This function calls:
rand Random state from a discrete belief.
get Get for GBeliefs.
rand Random state from a belief.
get Get function for the GMixture object.
rand Generates random points on a GMixture.
get Gaussian object get function.
rand Generates random ponts on a Gaussian.
get Get function for CS_CO_CA_POMDPs.
get Get function for CS_CO_DA_POMDPs.
get Get function for CS_CO_POMDPs.
get Get function for CS_DO_CA_POMDPs.
get Get function for CS_DO_DA_POMDPs.
get Get function for CS_POMDPs.
get Get function for DS_CO_CA_POMDPs.
get Get function for DS_CO_DA_POMDPs.
get Get function for DS_DO_CA_POMDPs.
get Get function for DS_DO_DA_POMDPs.
get Get functio for POMDPs.
rand Random state from a continuous space.
rand Random state from a discrete space.
This function is called by:
BeliefPrediction Belief evolution under a given action.
SimulationStep Executes one step of a POMDP simulation.
SOURCE CODE
function bOut=Prediction(b,t,Sp)
%   Belief evolution given a transition model.
%
%   Updates a particle-based belief with a given transiton probability function, 't'.
%   Function 't' is the outcome of GetActionModelFixedA for the corresponding
%   action model.
%
%   Note that the prediction and update steps using particles are tied
%   together (see Section 5.3.2 of the paper). However, for compatibility
%   with the rest of belief representations it is nice to have separate
%   Prediction and Update functions.
%   Here we store a backup of the particles (to use them in the Update) and
%   we randomly modify them using the action model.
  bOut=b;
  bOut.noiselessMovedSamples=bOut.samples+repmat(get(t,'mean'),1,bOut.np);
  bOut.noise=get(t,'covariance');
  for i=1:b.np
    bOut.samples(:,i)=rand(t+bOut.samples(:,i));
  end