Description of Update
Update
PURPOSE
Belief evolution under an observation model.
SYNOPSIS
function bOut=Update(b,po,Sp)
DESCRIPTION
   Belief evolution under an observation model.
   Corrects a belief with the information given by the observation model,
   'po'.
   'po' is derived with GetObservationModelFixedO for the
   corresponding obs model.
   Note that we use the backed up samples possibly created in a
   Predicition step before. If no prediction step was exectued before,
   the backup and the samples point to the same data.
CROSS-REFERENCE INFORMATION
This function calls:
rand Random state from a discrete belief.
PBelief Particle-based belief constructor.
rand Random state from a belief.
Crop Limits all means to be inside the given space.
Value Evaluates a GMixture.
rand Generates random points on a GMixture.
Crop Forces the Gaussian mean to be in a given space.
Gaussian Gaussian construtor.
Value Evaluation of a Gaussian.
rand Generates random ponts on a Gaussian.
RandVector Selects and element from a discrete probability distribution.
Crop Forces a state to be in a given continuous sub-space.
rand Random state from a continuous space.
Crop Forces a state to be in a given discrete space.
rand Random state from a discrete space.
This function is called by:
DiscretizeObsModel Discretizes the observation model on the observation side.
Update Belief evolution under an observation model.
SimulationStep Executes one step of a POMDP simulation.
SOURCE CODE
function bOut=Update(b,po,Sp)
%   Belief evolution under an observation model.
%
%   Corrects a belief with the information given by the observation model,
%   'po'.
%   'po' is derived with GetObservationModelFixedO for the
%   corresponding obs model.
%
%   Note that we use the backed up samples possibly created in a
%   Predicition step before. If no prediction step was exectued before,
%   the backup and the samples point to the same data.
  c=arrayfun(@(s)(Value(po,s)),b.noiselessMovedSamples);
  w=b.w.*c;
  g=cell(1,b.np);
  for i=1:b.np
    g{i}=Gaussian(b.samples(:,i),b.noise);
  end
  ns=zeros(b.ss,b.np);
  nw=zeros(1,b.np);
  for i=1:b.np
    j=RandVector(w);
    ns(:,i)=Crop(Sp,rand(g{j}));
    nw(i)=Value(po,ns(:,i))/c(j);
  end
  bOut=PBelief(nw,ns);