Description of Discretize
Discretize
PURPOSE
Discretizes the state space of the CS_DO_DA_POMDP.
SYNOPSIS
function DP=Discretize(CP,n)
DESCRIPTION
  Discretizes the state space of the CS_DO_DA_POMDP.
  Converts a POMDP on a continuous state space (but discrete actions and
  observations) into a POMDP on a discrete state space.
  Parameter 'n' is the number of states of the output state space.
  This procedure samples 'n' states (uniformly for one-dimensional
  continuous state spaces and randomly for higher dimenional spaces) and
  adjust the action/observation/reward models acordingly.
  The name given to the output POMDP is the same as that of the input
  POMDP but adding '-discrete' at the end. Remember that this name is used
  to generate files of planning results.
CROSS-REFERENCE INFORMATION
This function calls:
DiscretizeActionModel Generates a new action model discretizing the action space.
DiscretizeActionModel Produces a new action model discretizing the state space.
DiscretizeActionModel Generates a new action model discretizing the action space of the given model.
get Get for GBeliefs.
get Get function for the GMixture object.
get Gaussian object get function.
DiscretizeObsModel Discretizes the observation model on the observation side.
DiscretizeObsModel Discretizes the observation model on the state side.
DiscretizeObsModel Discretizes the observation model on the observation side.
DiscretizeActionModel Discretizes the action space CS_CO_CA_POMDP.
DiscretizeObsModel Discretizes the observation model on the observation side.
get Get function for CS_CO_CA_POMDPs.
DiscretizeObsModel Discretizes the observation model on the observation side.
get Get function for CS_CO_DA_POMDPs.
get Get function for CS_CO_POMDPs.
DiscretizeActionModel Discretizes the action space CS_DO_CA_POMDP.
get Get function for CS_DO_CA_POMDPs.
Discretize Discretizes the state space of the CS_DO_DA_POMDP.
get Get function for CS_DO_DA_POMDPs.
get Get function for CS_POMDPs.
DiscretizeObsModel Discretizes the observation model on the observation side.
get Get function for DS_CO_CA_POMDPs.
DiscretizeObsModel Discretizes the observation model on the observation side.
get Get function for DS_CO_DA_POMDPs.
DiscretizeActionModel Discretizes the action space DS_DO_CA_POMDP.
get Get function for DS_DO_CA_POMDPs.
DS_DO_DA_POMDP DS_DO_DA_POMDP constructor.
get Get function for DS_DO_DA_POMDPs.
DiscretizeActionModel Discretizes a POMDP on the action side.
DiscretizeObsModel Discretizes a POMDP on the observation side.
get Get functio for POMDPs.
DiscretizeRewardModel Discretizes the reward model on the action side.
DiscretizeRewardModel Discretizes the reward model on the state side.
Discretize Converts a continuous space into a discrete one.
This function is called by:
GenerateFigure7aData Generates the data for Figure 7-left.
GetTest1pParameters The example on Figure 8.
MakeFigure7 Generates Figure 7.
DiscretizeObsModel Discretizes the observation model on the observation side.
DiscretizeActionModel Discretizes the action space CS_CO_CA_POMDP.
DiscretizeActionModel Discretizes the action space CS_DO_CA_POMDP.
Discretize Discretizes the state space of the CS_DO_DA_POMDP.
DiscretizeActionModel Discretizes the action space DS_DO_CA_POMDP.
SOURCE CODE
function DP=Discretize(CP,n)
%  Discretizes the state space of the CS_DO_DA_POMDP.
%
%  Converts a POMDP on a continuous state space (but discrete actions and
%  observations) into a POMDP on a discrete state space.
%  Parameter 'n' is the number of states of the output state space.
%  This procedure samples 'n' states (uniformly for one-dimensional
%  continuous state spaces and randomly for higher dimenional spaces) and
%  adjust the action/observation/reward models acordingly.
%  The name given to the output POMDP is the same as that of the input
%  POMDP but adding '-discrete' at the end. Remember that this name is used
%  to generate files of planning results.
%
  nameC=get(CP,'name');
  CS=get(CP,'StateSpace');
  CA=get(CP,'ActionSpace');
  CO=get(CP,'ObsSpace');
  COM=get(CP,'ObsModel');
  CAM=get(CP,'ActionModel');
  CRM=get(CP,'RewardModel');
  DS=Discretize(CS,n);
  DA=CA;
  DO=CO;
  DAM=DiscretizeActionModel(CAM,DS);
  DOM=DiscretizeObsModel(COM,DS);
  DRM=DiscretizeRewardModel(CRM,DS);
  gamma=get(CP,'gamma');
  nameD=sprintf('%s-discrete-%u',nameC,n);
  DP=DS_DO_DA_POMDP(nameD,DS,DA,DO,DAM,DOM,DRM,gamma);