Description of max
max
PURPOSE
Upper bound of a CSpace
SYNOPSIS
function m=max(S)
DESCRIPTION
 Upper bound of a CSpace
 Returns the upper bounds of a continuous space for all dimensions as a
 column vector.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
MaxAlpha Returns the maximizing alpha-element for a belief.
OptimalAction Returns the optimal action for a given belief.
plot Plots a Gaussian mixture.
Gaussian Gaussian construtor.
DiscretizeObsModel Discretizes the observation model on the observation side.
plot Plots the CS_CO_ObsModel
DiscretizeObsModel Discretizes the observation model on the observation side.
CS_CO_CA_POMDP CS_CO_CA_POMDP constructor.
CS_DO_CA_POMDP CS_DO_CA_POMDP constructor.
ComputeAlpha_a Compute the alpha_i_n-element for the given action and belief.
Backup Backup for a given belief (continuous state version).
DS_CO_CA_POMDP DS_CO_CA_POMDP constructor.
DS_DO_CA_POMDP DS_CO_DA_POMDP constructor.
ComputeAlpha_a Compute the alpha_i_n-element for the given action and belief.
Backup Backupt for a given belief (discrete state version).
Perseus The Perseus point-based POMDP solver.
iPerseus Improved version of Perseus.
plot Plots the CS_CA_RewardModel
Crop Forces a state to be in a given continuous sub-space.
UniformDistribution Uniform probability on a continuous space.
Crop Forces a state to be in a given discrete space.
SOURCE CODE
function m=max(S)
% Upper bound of a CSpace
%
% Returns the upper bounds of a continuous space for all dimensions as a
% column vector.
  m=S.max;