Description of min
min
PURPOSE
Lower bound of a CSpace
SYNOPSIS
function m=min(S)
DESCRIPTION
 Lower bound of a CSpace
 Returns the lower bounds of a continuous space for all dimensions as a
 column vector.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
Distance Distance between beliefs.
CompressGR Gaussian mixture compression using the Golberger and Roweis method.
Distance Approximated Kullback-Leibler distance between Gaussian mixture.
get Get function for the GMixture object.
plot Plots a Gaussian mixture.
DiscretizeObsModel Discretizes the observation model on the observation side.
plot Plots the CS_CO_ObsModel
SampleBeliefs Samples a set of beliefs from a POMDP.
minReward Lower bound of the minimal possible reward.
plot Plots the CS_CA_RewardModel
minReward Lower bound of the minimal possible reward.
minReward Lower bound of the minimal possible reward.
minReward Lower bound of the minimal possible reward.
Crop Forces a state to be in a given continuous sub-space.
Crop Forces a state to be in a given discrete space.
SOURCE CODE
function m=min(S)
% Lower bound of a CSpace
%
% Returns the lower bounds of a continuous space for all dimensions as a
% column vector.
  m=S.min;