Description of UniformProbability
UniformProbability
PURPOSE
Uniform probability value on a continuous space.
SYNOPSIS
function p=UniformProbability(CS)
DESCRIPTION
   Uniform probability value on a continuous space.
   Returns the value of a uniform probability defined on the bounds of the
   given continuous space.
   See also @CSpace/UniformDistribution.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
CS_CO_ObsModel CS_CO_ObsModel constructor.
DiscretizeObsModel Discretizes the observation model on the observation side.
GetObsModelFixedO Defines p(o|s) for a fixed 'o'.
CS_DO_ObsModel CS_DO_ObsModel constructor.
GetObsModelFixedO Defines p(o|s) for a fixed 'o'.
SOURCE CODE
function p=UniformProbability(CS)
%   Uniform probability value on a continuous space.
%
%   Returns the value of a uniform probability defined on the bounds of the
%   given continuous space.
%
%   See also @CSpace/UniformDistribution.
  p=prod(ones(1,CS.dim)./CS.range);