Description of CS_DO_ObsModel
CS_DO_ObsModel
PURPOSE
CS_DO_ObsModel constructor.
SYNOPSIS
function OM=CS_DO_ObsModel(varargin)
DESCRIPTION
   CS_DO_ObsModel constructor.
   Defines an observation model (p(o|s))  on continuous state and discrete
   observation spaces.
   Parameters
    S: Continuous state space.
    O: Discrete observation space.
    p: A cell array with one GMixture (in 's') for each observation.
CROSS-REFERENCE INFORMATION
This function calls:
size Returns the size of a policy.
rand Random state from a discrete belief.
rand Random state from a belief.
Value Evaluates a GMixture.
rand Generates random points on a GMixture.
Value Evaluation of a Gaussian.
rand Generates random ponts on a Gaussian.
ObsModel ObsModel constructor.
UniformProbability Uniform probability value on a continuous space.
dim Dimensionality of a continuous space.
rand Random state from a continuous space.
UniformProbability Uniform probability value on a discrete space.
dim Dimensionality of a discrete space.
rand Random state from a discrete space.
This function is called by:
GetTest1Parameters The example on Figure 1.
DiscretizeObsModel Discretizes the observation model on the observation side.
SOURCE CODE
function OM=CS_DO_ObsModel(varargin)
%   CS_DO_ObsModel constructor.
%
%   Defines an observation model (p(o|s))  on continuous state and discrete
%   observation spaces.
%
%   Parameters
%    S: Continuous state space.
%    O: Discrete observation space.
%    p: A cell array with one GMixture (in 's') for each observation.
  switch nargin
    case 1
      if isa(varargin{1},'CS_DO_ObsModel')
        OM=varargin{1};
      else
        error('Wrong parameter type in CS_DO_ObsModel constructor');
      end
    case 3
      if isa(varargin{1},'CSpace')
        OM.S=varargin{1};
      else
        error('Wrong parameter type in CS_DO_ObsModel constructor');
      end
      if isa(varargin{2},'DSpace')
        OM.O=varargin{2};
      else
        error('Wrong parameter type in CS_DO_ObsModel constructor');
      end
      if isa(varargin{3},'cell')
        OM.p=varargin{3};
      else
        error('Wrong parameter type in CS_DO_ObsModel constructor');
      end
      no=dim(OM.O);
      if no~=size(OM.p,2)
        error('Size missmatch in DS_CO_ObsModel constructor');
      end
      % p(s) should be uniform in 's'. We compute p(s) as
      %      p(s) = sum_o p(o,s)
      % and, assuming it is constant, we scale p(o,s) so that p(s) is
      % actually uniform.
      o=OM.p{1};
      for i=2:no
        o=o+OM.p{i};
      end
      % Scale factor to apply = What it should be (UniformProbability(OM.S))
      % vs. what actually is (Value(o,Center(OM.S)))
      % We estimate p(s) via sampling (small variations can occur)
      ps=0;
      for i=1:10
        ps=ps+Value(o,rand(OM.S));
      end
      ps=ps/10;
      scale=UniformProbability(OM.S)/ps;
      for i=1:no
        OM.p{i}=OM.p{i}*scale;
      end
      OMBase=ObsModel();
      OM=class(OM,'CS_DO_ObsModel',OMBase);
    otherwise
      error('Wrong number of parameters in CS_DO_ObsModel constructor');
  end