Description of ObsModel
ObsModel
PURPOSE
ObsModel constructor.
SYNOPSIS
function OM=ObsModel(varargin)
DESCRIPTION
   ObsModel constructor.
   Constructor of the observatin model base object.
   This is used to be able to execute queries such as
       isa(o,'ObsModel')
   and to implement geniric observation model functions.
   See also @ObsModel/Update.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
CS_CO_ObsModel CS_CO_ObsModel constructor.
CS_DO_ObsModel CS_DO_ObsModel constructor.
DS_CO_ObsModel DS_CO_ObsModel constructor.
DS_DO_ObsModel DS_DO_ObsModel constructor.
SOURCE CODE
function OM=ObsModel(varargin)
%   ObsModel constructor.
%
%   Constructor of the observatin model base object.
%   This is used to be able to execute queries such as
%       isa(o,'ObsModel')
%   and to implement geniric observation model functions.
%
%   See also @ObsModel/Update.
  switch nargin
    case 0
      OM.dummy=1;
      OM=class(OM,'ObsModel');
    case 1
      if isa(varargin{1},'ObsModel')
        OM=varargin{1};
      else
        error('Wrong parameter type in ObsModel constructor');
      end
    otherwise
      error('Wrong number of parameters in ObsModel constructor');
  end