Description of Crop
Crop
PURPOSE
Forces the Gaussian mean to be in a given space.
SYNOPSIS
function gOut=Crop(g,Sp)
DESCRIPTION
   Forces the Gaussian mean to be in a given space.
   Crops the mean of a given Gaussian so that is is inside the
   continuous sub-space defined by Sp.
   See also CSpace.
CROSS-REFERENCE INFORMATION
This function calls:
Crop Limits all means to be inside the given space.
Crop Forces the Gaussian mean to be in a given space.
Crop Forces a state to be in a given continuous sub-space.
Crop Forces a state to be in a given discrete space.
This function is called by:
Prediction Belief evolution under the given action.
DiscretizeActionModel Produces a new action model discretizing the state space.
Prediction Belief evolution under the given action.
Prediction Belief evolution given a transition model.
Update Belief evolution under an observation model.
Update Belief evolution under an observation model.
Crop Limits all means to be inside the given space.
Crop Forces the Gaussian mean to be in a given space.
SampleBeliefs Samples a set of beliefs from a POMDP.
SOURCE CODE
function gOut=Crop(g,Sp)
%   Forces the Gaussian mean to be in a given space.
%
%   Crops the mean of a given Gaussian so that is is inside the
%   continuous sub-space defined by Sp.
%
%   See also CSpace.
  gOut=g;
  gOut.m=Crop(Sp,g.m);