Description of get
get
PURPOSE
Gaussian object get function.
SYNOPSIS
function out=get(g,field)
DESCRIPTION
   Gaussian object get function.
   Returns the information associated with a Gaussian
   Possible queries are
      - dim: The dimensionality of the space where the Gaussian is defined
      - mean:  The mean vector.
      - covariance: The covariance matrix.
      - invCovariance: The inverse of the covariance matrix.
      - volume: The volume of the ellipsoid defined from the covariance matrix.
      - normalizationFactor: The normalization factor for a Gaussian (the constant
        that multiplies the exponential defining the Gaussian
        distribution).
      - ellipse: Returns a line representing the iso-countour of the
        ellipse defined from the mean and covariance at a 95% confidence
        value. For higher-dimensional Gaussians, we marginalize and only
        use the first 2 components of the Gaussians.
CROSS-REFERENCE INFORMATION
This function calls:
size Returns the size of a policy.
This function is called by:
DiscretizeActionModel Produces a new action model discretizing the state space.
get Get for GBeliefs.
Prediction Belief evolution given a transition model.
GenerateFigure7aData Generates the data for Figure 7-left.
GetTest1caParameters The example on Figure 10.
GetTest1coParameters The example on Figure 11.
GetTest1pParameters The example on Figure 8.
MakeFigure1 Generates Figure 1.
MakeFigure3 Generates Figure 3.
MakeFigure7 Generates Figure 7.
Covariance Average covariance of a Gaussian mixture.
FuseComponents Fuses a Gaussian mixture into a single Gaussian.
Mean Mean of a Gmixture.
ProductInt Product and marginalization of two GMixtures.
plot Plots a Gaussian mixture.
rand Generates random points on a GMixture.
plot Plots a Gaussian.
GetPOMDPSolutionStatistics Collects statistics with the outcome of an experiment.
TestRep Executes many times of Perseus on a given problem.
TestRepWithStatistics Executes many times Perseus on a given problem and collects statistics.
DiscretizeObsModel Discretizes the observation model on the observation side.
DiscretizeActionModel Discretizes the action space CS_CO_CA_POMDP.
DiscretizeObsModel Discretizes the observation model on the observation side.
get Get function for CS_CO_CA_POMDPs.
DiscretizeObsModel Discretizes the observation model on the observation side.
get Get function for CS_CO_DA_POMDPs.
ComputeAlpha_a Compute the alpha_i_n-element for the given action and belief.
get Get function for CS_CO_POMDPs.
DiscretizeActionModel Discretizes the action space CS_DO_CA_POMDP.
get Get function for CS_DO_CA_POMDPs.
Discretize Discretizes the state space of the CS_DO_DA_POMDP.
get Get function for CS_DO_DA_POMDPs.
ComputeAlpha_a Compute the alpha_i_n-element for the given action and belief.
Alpha0 Alpha-element for the first Perseus iteration (continuos state version).
Backup Backup for a given belief (continuous state version).
ComputeAlpha_j_a_o Computes a particular alpha-element.
get Get function for CS_POMDPs.
DiscretizeObsModel Discretizes the observation model on the observation side.
get Get function for DS_CO_CA_POMDPs.
DiscretizeObsModel Discretizes the observation model on the observation side.
get Get function for DS_CO_DA_POMDPs.
DiscretizeActionModel Discretizes the action space DS_DO_CA_POMDP.
get Get function for DS_DO_CA_POMDPs.
get Get function for DS_DO_DA_POMDPs.
ComputeAlpha_a Compute the alpha_i_n-element for the given action and belief.
Alpha0 Alpha-element for the first Perseus iteration (discrete state version).
Backup Backupt for a given belief (discrete state version).
ComputeAlpha_j_a_o Computes a particular alpha-element.
ComputeAlphas_j_a_o Computes the set of al possible alpha-elements.
DiscretizeActionModel Discretizes a POMDP on the action side.
DiscretizeObsModel Discretizes a POMDP on the observation side.
RandomAction Draws a random action from a POMDP.
SampleBeliefs Samples a set of beliefs from a POMDP.
SimulateFrom Simulates a POMDP from a given belief.
SimulationStep Executes one step of a POMDP simulation.
UniformDistribution Uniform distribution in the POMDP state space.
minReward Lower bound of the minimal possible reward.
minReward Lower bound of the minimal possible reward.
SOURCE CODE
function out=get(g,field)
%   Gaussian object get function.
%
%   Returns the information associated with a Gaussian
%   Possible queries are
%      - dim: The dimensionality of the space where the Gaussian is defined
%      - mean:  The mean vector.
%      - covariance: The covariance matrix.
%      - invCovariance: The inverse of the covariance matrix.
%      - volume: The volume of the ellipsoid defined from the covariance matrix.
%      - normalizationFactor: The normalization factor for a Gaussian (the constant
%        that multiplies the exponential defining the Gaussian
%        distribution).
%      - ellipse: Returns a line representing the iso-countour of the
%        ellipse defined from the mean and covariance at a 95% confidence
%        value. For higher-dimensional Gaussians, we marginalize and only
%        use the first 2 components of the Gaussians.
  switch field
    case 'dim'
      out=g.dim;
        case 'mean'
            out=g.m;
        case 'covariance'
            out=g.S;
        case 'information'
            out=g.iS;
        case 'volume'
            out=g.d;
        case 'normalizationFactor'
            out=g.ct;
        case 'ellipse'
            S2d=g.S(1:2,1:2);
      % For 2 dim, a Xi squared distribution gives that the
      % 90% confidence level is obtained at 2.1459
      R=chol(S2d);
      y = 2.1459*[cos(0:0.1:2*pi);sin(0:0.1:2*pi)];
      el=R*y;
      out = [el el(:,1)]+repmat(g.m(1:2),1,size(el,2)+1);
    otherwise
      error('Unknow field in Gaussian get');
    end