Description of plot
plot
PURPOSE
Plots a Gaussian.
SYNOPSIS
function h=plot(g,varargin)
DESCRIPTION
  Plots a Gaussian.
  Plots a Gaussian. For one-dimensinal Gaussians produces a
  one-dimensional plot. For higher dimensional Gaussians an ellipse
  representing the marginal of the Gaussian on the two first dimensions is
  shown.
  The fuction accepts an optional parameter with the color for the plot.
  Returns:
    h: The handler of the line/ellipse representing the Gaussian.
CROSS-REFERENCE INFORMATION
This function calls:
plot Plots a discrete belief.
get Get for GBeliefs.
plot Displays a particle-based belief.
Value Evaluates a GMixture.
get Get function for the GMixture object.
plot Plots a Gaussian mixture.
set Set method for Gaussian mixtures.
Value Evaluation of a Gaussian.
get Gaussian object get function.
plot Plots a Gaussian.
plot Plots the CS_CO_ObsModel
get Get function for CS_CO_CA_POMDPs.
get Get function for CS_CO_DA_POMDPs.
get Get function for CS_CO_POMDPs.
get Get function for CS_DO_CA_POMDPs.
get Get function for CS_DO_DA_POMDPs.
get Get function for CS_POMDPs.
get Get function for DS_CO_CA_POMDPs.
get Get function for DS_CO_DA_POMDPs.
get Get function for DS_DO_CA_POMDPs.
get Get function for DS_DO_DA_POMDPs.
get Get functio for POMDPs.
set Set function for PODMP (base type)
plot Plots the CS_CA_RewardModel
This function is called by:
plot Plots a discrete belief.
MakeFigure1 Generates Figure 1.
MakeFigure3 Generates Figure 3.
MakeFigure6 Generates Figure 6.
MakeFigure7 Generates Figure 7.
MakeFigure9 Generates Figure 9.
plot Plots a Gaussian.
SOURCE CODE
function h=plot(g,varargin)
%  Plots a Gaussian.
%
%  Plots a Gaussian. For one-dimensinal Gaussians produces a
%  one-dimensional plot. For higher dimensional Gaussians an ellipse
%  representing the marginal of the Gaussian on the two first dimensions is
%  shown.
%  The fuction accepts an optional parameter with the color for the plot.
%
%  Returns:
%    h: The handler of the line/ellipse representing the Gaussian.
  if g.d==0
        h=0;
    else
        if g.dim==1
              r=3*sqrt(g.S); % represent the Gaussian from -3*sigma to 3*sigma
                n=100; %points of the curbe representing the gaussain
                X=(-r:(2*r)/(n-1):r)+g.m;
                Y=Value(g,X);
                plot(X,Y);
        else
            h=line([g.m(1) g.m(1)],[g.m(2) g.m(2)]);
            set(h, 'marker','*');
            if nargin>1
                set(h, 'Color',varargin{1});
            end
            el=get(g,'ellipse');
            h = line(el(1,:),el(2,:));
            if nargin>1
                set(h, 'Color',varargin{1});
            end
        end
    end