Description of ProductNormFactor
ProductNormFactor
PURPOSE
Normalization constant of the product of two Gaussians.
SYNOPSIS
function d=ProductNormFactor(g1,g2)
DESCRIPTION
   Normalization constant of the product of two Gaussians.
   Returns the 'un-normalization' factor resulting from multiplying two
   Gaussians.
   See also Product, mtimes.
CROSS-REFERENCE INFORMATION
This function calls:
Value Evaluates a GMixture.
Gaussian Gaussian construtor.
Value Evaluation of a Gaussian.
This function is called by:
Product Product of two Gaussians.
SOURCE CODE
function d=ProductNormFactor(g1,g2)
%   Normalization constant of the product of two Gaussians.
%
%   Returns the 'un-normalization' factor resulting from multiplying two
%   Gaussians.
%
%   See also Product, mtimes.
  d=Value(Gaussian(g2.m,g1.S+g2.S),g1.m);