Description of Backup
Backup
PURPOSE
Backup for a given belief (continuous state version).
SYNOPSIS
function [alpha a v]=Backup(P,b,V,Alphas_j_a_o)
DESCRIPTION
   Backup for a given belief (continuous state version).
   Belief backup function for POMDP defined on continuous state spaces.
   The backup operator is introduced in Section 4 (page 12) but without any
   assumption on the type of state space.
   This function corresponds to the particularization of the backup for
   continuous state spaces given on Section 5.2 of the
   paper (pages 15 and 16).
   This function basically computes one Alpha-element for each action and
   selects the one that gives higher value for the given belief.
   Parameters:
     P: The POMDP
     b: The belief
     V: The previous policy/value function/set of alpha-elements.
     Alphas_j_a_o: The set of pre-compute alpha_j_a_o elements. If empty,
                   the alpha_j_a_o elements are computed on the fly.
CROSS-REFERENCE INFORMATION
This function calls:
Expectation Expectation between a belief and a alpha-element.
Expectation Expectation between a belief and a alpha-element.
get Get for GBeliefs.
Expectation Expectation between a belief and a alpha-element.
Compress Gaussian mixutre compression.
get Get function for the GMixture object.
get Gaussian object get function.
get Get function for CS_CO_CA_POMDPs.
get Get function for CS_CO_DA_POMDPs.
ComputeAlpha_a Compute the alpha_i_n-element for the given action and belief.
get Get function for CS_CO_POMDPs.
get Get function for CS_DO_CA_POMDPs.
get Get function for CS_DO_DA_POMDPs.
ComputeAlpha_a Compute the alpha_i_n-element for the given action and belief.
get Get function for CS_POMDPs.
get Get function for DS_CO_CA_POMDPs.
get Get function for DS_CO_DA_POMDPs.
get Get function for DS_DO_CA_POMDPs.
get Get function for DS_DO_DA_POMDPs.
ComputeAlpha_a Compute the alpha_i_n-element for the given action and belief.
get Get functio for POMDPs.
dim Dimensionality of a continuous space.
max Upper bound of a CSpace
dim Dimensionality of a discrete space.
This function is called by:
Perseus The Perseus point-based POMDP solver.
iPerseus Improved version of Perseus.
SOURCE CODE
function [alpha a v]=Backup(P,b,V,Alphas_j_a_o)
%   Backup for a given belief (continuous state version).
%
%   Belief backup function for POMDP defined on continuous state spaces.
%   The backup operator is introduced in Section 4 (page 12) but without any
%   assumption on the type of state space.
%   This function corresponds to the particularization of the backup for
%   continuous state spaces given on Section 5.2 of the
%   paper (pages 15 and 16).
%
%   This function basically computes one Alpha-element for each action and
%   selects the one that gives higher value for the given belief.
%
%   Parameters:
%     P: The POMDP
%     b: The belief
%     V: The previous policy/value function/set of alpha-elements.
%     Alphas_j_a_o: The set of pre-compute alpha_j_a_o elements. If empty,
%                   the alpha_j_a_o elements are computed on the fly.
  A=get(P,'ActionSpace'); % This is suposed to be discrete
  if isa(A,'CSpace')
    error('The Action Space must be discrete at this point');
  end
  Elements_a=arrayfun(@(a)(ComputeAlpha_a(P,V,b,a,Alphas_j_a_o)),1:dim(A),'UniformOutput',false);
  fprintf('a');
  [v na]=max(cellfun(@(ea)(Expectation(b,ea)),Elements_a));
  fprintf('c');
  alpha=Compress(Elements_a{na},P.maxAlphaC);
  v=Expectation(b,alpha);
  a=A(na);