Description of ComputeAlphas_j_a_o
ComputeAlphas_j_a_o
PURPOSE
Computes the set of al possible alpha-elements.
SYNOPSIS
function As=ComputeAlphas_j_a_o(P,V)
DESCRIPTION
   Computes the set of al possible alpha-elements.
   Compute the whole se of alpha_j_a_o elements.
   This function only works for POMDP with discrete action and observation
   spaces.
   The function is a generic implementation that uses the particular
   ComputeAlpha_j_a_o function of the corresponding type of POMDP.
   Parameters
     P: The POMDP.
     V: The previous policy/value function/set of alpha-elements.
   See also @DS_ComputeAlpha_j_a_o, @CS_ComputeAlpha_j_a_o.
CROSS-REFERENCE INFORMATION
This function calls:
size Returns the size of a policy.
get Get for GBeliefs.
get Get function for the GMixture object.
get Gaussian object get function.
get Get function for CS_CO_CA_POMDPs.
get Get function for CS_CO_DA_POMDPs.
get Get function for CS_CO_POMDPs.
get Get function for CS_DO_CA_POMDPs.
get Get function for CS_DO_DA_POMDPs.
ComputeAlpha_j_a_o Computes a particular alpha-element.
get Get function for CS_POMDPs.
get Get function for DS_CO_CA_POMDPs.
get Get function for DS_CO_DA_POMDPs.
get Get function for DS_DO_CA_POMDPs.
get Get function for DS_DO_DA_POMDPs.
ComputeAlpha_j_a_o Computes a particular alpha-element.
get Get functio for POMDPs.
dim Dimensionality of a continuous space.
dim Dimensionality of a discrete space.
This function is called by:
Perseus The Perseus point-based POMDP solver.
iPerseus Improved version of Perseus.
SOURCE CODE
function As=ComputeAlphas_j_a_o(P,V)
%   Computes the set of al possible alpha-elements.
%
%   Compute the whole se of alpha_j_a_o elements.
%
%   This function only works for POMDP with discrete action and observation
%   spaces.
%
%   The function is a generic implementation that uses the particular
%   ComputeAlpha_j_a_o function of the corresponding type of POMDP.
%
%   Parameters
%     P: The POMDP.
%     V: The previous policy/value function/set of alpha-elements.
%
%   See also @DS_ComputeAlpha_j_a_o, @CS_ComputeAlpha_j_a_o.
  A=get(P,'ActionSpace');
  O=get(P,'ObsSpace');
  if isa(A,'DSpace') && isa(O,'DSpace')
    na=dim(A);
    no=dim(O);
    nj=size(V);
    ro=1:no;
    As=cell(nj,na,no);
    for j=1:nj
      for a=1:na
        As(j,a,:)=arrayfun(@(o)(ComputeAlpha_j_a_o(P,V,j,a,o)),ro,'UniformOutput',false);
      end
    end
  else
    As={};
  end