Description of POMDP
POMDP
PURPOSE
POMDP constructor.
SYNOPSIS
function P=POMDP(varargin)
DESCRIPTION
   POMDP constructor.
   Base object for all POMDP objects.
   Parameters
     name: name for the POMDP.
     gamma: discount factor.
   See also DS_POMDP, CS_POMDP.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
GenerateFigure5Data Generates the data for Figure 5.
GenerateFigure7aData Generates the data for Figure 7-left.
GetHallwayParameters The hallway discrete POMDP.
GetTest1Parameters The example on Figure 1.
GetTest1caParameters The example on Figure 10.
GetTest1coParameters The example on Figure 11.
GetTest1pParameters The example on Figure 8.
MakeFigure1 Generates Figure 1.
MakeFigure3 Generates Figure 3.
MakeFigure6 Generates Figure 6.
MakeFigure7 Generates Figure 7.
MakeFigure9 Generates Figure 9.
GetPOMDPSolutionStatistics Collects statistics with the outcome of an experiment.
TestOne Samples beliefs and executes Perseus on a given problem.
TestRep Executes many times of Perseus on a given problem.
CS_POMDP CS_POMDP constructor.
DS_POMDP DS_POMDP constructor.
UniformDistribution Uniform distribution in the POMDP state space.
SOURCE CODE
function P=POMDP(varargin)
%   POMDP constructor.
%
%   Base object for all POMDP objects.
%
%   Parameters
%     name: name for the POMDP.
%     gamma: discount factor.
%
%   See also DS_POMDP, CS_POMDP.
  switch nargin
    case 1
      if isa(varargin{1},'POMDP')
        P=varargin{1};
      else
        error('Wrong parameter type in POMDP constructor');
      end
    case 2
      if isa(varargin{1},'char')
        P.name =varargin{1};
      else
        error('Wrong parameter type in POMDP constructor');
      end
      if isa(varargin{2},'double')
        P.gamma =varargin{2};
      else
        error('Wrong parameter type in POMDP constructor');
      end
      P=class(P,'POMDP');
    otherwise
      error('Wrong number of parameters in POMDP constructor');
  end