Description of RandomAction
RandomAction
PURPOSE
Draws a random action from a POMDP.
SYNOPSIS
function a=RandomAction(P)
DESCRIPTION
   Draws a random action from a POMDP.
   Selects a random action from the action model associated with the
   POMPD.
CROSS-REFERENCE INFORMATION
This function calls:
rand Random state from a discrete belief.
get Get for GBeliefs.
rand Random state from a belief.
get Get function for the GMixture object.
rand Generates random points on a GMixture.
get Gaussian object get function.
rand Generates random ponts on a Gaussian.
get Get function for CS_CO_CA_POMDPs.
get Get function for CS_CO_DA_POMDPs.
get Get function for CS_CO_POMDPs.
get Get function for CS_DO_CA_POMDPs.
get Get function for CS_DO_DA_POMDPs.
get Get function for CS_POMDPs.
get Get function for DS_CO_CA_POMDPs.
get Get function for DS_CO_DA_POMDPs.
get Get function for DS_DO_CA_POMDPs.
get Get function for DS_DO_DA_POMDPs.
get Get functio for POMDPs.
rand Random state from a continuous space.
rand Random state from a discrete space.
This function is called by:
Perseus The Perseus point-based POMDP solver.
iPerseus Improved version of Perseus.
SOURCE CODE
function a=RandomAction(P)
%   Draws a random action from a POMDP.
%
%   Selects a random action from the action model associated with the
%   POMPD.
%
 a=rand(get(P,'ActionSpace'));