Description of set
set
PURPOSE
Set function for PODMP (base type)
SYNOPSIS
function P=set(P,field,value)
DESCRIPTION
 Set function for PODMP (base type)
 Allows to change some fields of the basic POMDP structure
 Possible fields to change are
    - gamma (discount factor)
    - name (name given to the POMDP. Used to generate output files).
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
plot Displays a particle-based belief.
GetTest1pParameters The example on Figure 8.
MakeFigure1 Generates Figure 1.
MakeFigure3 Generates Figure 3.
MakeFigure4 Generates Figure 4.
MakeFigure5 Generates Figure 5.
MakeFigure6 Generates Figure 6.
MakeFigure7 Generates Figure 7.
MakeFigure9 Generates Figure 9.
MakeFigureSimulation Generates the plots in Figures 2, 8, 10, and 11.
plot Plots a Gaussian mixture.
plot Plots a Gaussian.
SOURCE CODE
function P=set(P,field,value)
% Set function for PODMP (base type)
%
% Allows to change some fields of the basic POMDP structure
%
% Possible fields to change are
%    - gamma (discount factor)
%    - name (name given to the POMDP. Used to generate output files).
  switch field
    case 'gamma'
      P.gamma=value;
    case 'name'
      P.name=value;
    otherwise
      error('Unknown field in POMDP set');
  end