Description of SimulationStep
SimulationStep
PURPOSE
Executes one step of a POMDP simulation.
SYNOPSIS
function [s b o r]=SimulationStep(P,b,s,a)
DESCRIPTION
   Executes one step of a POMDP simulation.
   It updates the belief using the corresponding Prediction method and the
   given action and then corrects the belief using the corresponding
   Update method.
   The implementation of both the Prediction and Update methods are
   dependant on the nature of the beliefs.
   Parameters:
     P: The POMDP.
     b: The belief to update.
     s: The hidden state (used to query the observation and reward models)
     a: The action to execute.
   Outputs:
     s: The new hidden state.
     b: The new belief.
     o: The observation used in the Update.
     r: The reward obtained in the new attained (hidden) state.
   See also DBelief, GBelief, PBelief, SimulateFrom.
CROSS-REFERENCE INFORMATION
This function calls:
Prediction Belief evolution under the given action.
Prediction Belief evolution under the given action.
Prediction Belief evolution under the given action.
Prediction Belief evolution under the given action.
Prediction Belief evolution given a transition model.
Update Belief evolution under an observation model.
rand Random state from a discrete belief.
Prediction Belief evolution given a transition model.
Update Belief evolution under an observation model.
get Get for GBeliefs.
Prediction Belief evolution given a transition model.
Update Belief evolution under an observation model.
rand Random state from a belief.
get Get function for the GMixture object.
rand Generates random points on a GMixture.
get Gaussian object get function.
rand Generates random ponts on a Gaussian.
RandVector Selects and element from a discrete probability distribution.
GetObsModelFixedS Defines p(o|s) for a fixed 's'.
GetObsModelFixedS Defines p(o|s)
GetObsModelFixedS Defines p(o|s).
GetObsModelFixedS Defines p(o|s).
Update Belief evolution under an observation model.
get Get function for CS_CO_CA_POMDPs.
get Get function for CS_CO_DA_POMDPs.
get Get function for CS_CO_POMDPs.
get Get function for CS_DO_CA_POMDPs.
get Get function for CS_DO_DA_POMDPs.
get Get function for CS_POMDPs.
get Get function for DS_CO_CA_POMDPs.
get Get function for DS_CO_DA_POMDPs.
get Get function for DS_DO_CA_POMDPs.
get Get function for DS_DO_DA_POMDPs.
get Get functio for POMDPs.
Reward Evaluates the reward function.
Reward Evaluates the reward function.
Reward Evaluates the reward function.
Reward Evaluates the reward function.
rand Random state from a continuous space.
rand Random state from a discrete space.
This function is called by:
MakeFigure3 Generates Figure 3.
SampleBeliefs Samples a set of beliefs from a POMDP.
SimulateFrom Simulates a POMDP from a given belief.
SOURCE CODE
function [s b o r]=SimulationStep(P,b,s,a)
%   Executes one step of a POMDP simulation.
%
%   It updates the belief using the corresponding Prediction method and the
%   given action and then corrects the belief using the corresponding
%   Update method.
%   The implementation of both the Prediction and Update methods are
%   dependant on the nature of the beliefs.
%
%   Parameters:
%     P: The POMDP.
%     b: The belief to update.
%     s: The hidden state (used to query the observation and reward models)
%     a: The action to execute.
%
%   Outputs:
%     s: The new hidden state.
%     b: The new belief.
%     o: The observation used in the Update.
%     r: The reward obtained in the new attained (hidden) state.
%
%   See also DBelief, GBelief, PBelief, SimulateFrom.
  S=get(P,'StateSpace');
  [s b]=Prediction(P,s,b,a,S);
  po=GetObsModelFixedS(P,s);
  if isa(po,'double')
    o=RandVector(po);
  else
    o=rand(po);
  end
  b=Update(P,b,o,S);
  r=Reward(P,a,s);