Description of SimulateFrom
SimulateFrom
PURPOSE
Simulates a POMDP from a given belief.
SYNOPSIS
function r=SimulateFrom(P,V,start,n)
DESCRIPTION
   Simulates a POMDP from a given belief.
   Simulates a POMDP from a given belief ('start') for 'n' steps and using
   the given policy ('V') to decide the actions to execute.
   The functions drawns a state at random from the 'start' distribution
   and uses is as a hidden state in the simulation. This hidden state is
   used to query the observation and reward models.
   Returns the accumulated discounted reward fro the simulation.
   This function is basically used to get statistics for the policy
   derived after a planning session. As the elements in 'V' increase, the
   simulation can get quite time demanding. Actually, this is the most
   expensive step of the statistics collection that is more costly than
   the planning itself.
   See also GetPOMDPSolutionStatistics.
CROSS-REFERENCE INFORMATION
This function calls:
OptimalAction Returns the optimal action for a given belief.
empty Checks if a policy is empty.
rand Random state from a discrete belief.
get Get for GBeliefs.
rand Random state from a belief.
get Get function for the GMixture object.
rand Generates random points on a GMixture.
get Gaussian object get function.
rand Generates random ponts on a Gaussian.
get Get function for CS_CO_CA_POMDPs.
get Get function for CS_CO_DA_POMDPs.
get Get function for CS_CO_POMDPs.
get Get function for CS_DO_CA_POMDPs.
get Get function for CS_DO_DA_POMDPs.
get Get function for CS_POMDPs.
get Get function for DS_CO_CA_POMDPs.
get Get function for DS_CO_DA_POMDPs.
get Get function for DS_DO_CA_POMDPs.
get Get function for DS_DO_DA_POMDPs.
SimulationStep Executes one step of a POMDP simulation.
get Get functio for POMDPs.
rand Random state from a continuous space.
rand Random state from a discrete space.
This function is called by:
GetPOMDPSolutionStatistics Collects statistics with the outcome of an experiment.
SOURCE CODE
function r=SimulateFrom(P,V,start,n)
%   Simulates a POMDP from a given belief.
%
%   Simulates a POMDP from a given belief ('start') for 'n' steps and using
%   the given policy ('V') to decide the actions to execute.
%
%   The functions drawns a state at random from the 'start' distribution
%   and uses is as a hidden state in the simulation. This hidden state is
%   used to query the observation and reward models.
%
%   Returns the accumulated discounted reward fro the simulation.
%
%   This function is basically used to get statistics for the policy
%   derived after a planning session. As the elements in 'V' increase, the
%   simulation can get quite time demanding. Actually, this is the most
%   expensive step of the statistics collection that is more costly than
%   the planning itself.
%
%   See also GetPOMDPSolutionStatistics.
  A=get(P,'ActionSpace');
  noPolicy=empty(V);
  s=rand(start);
  b=start;
  r=0;
  gamma=1;
  for i=1:n
    if noPolicy
      a=rand(A);
    else
      a=OptimalAction(V,b);
    end
    [s b o r1]=SimulationStep(P,b,s,a);
    r=r+gamma*r1;
    gamma=gamma*P.gamma;
  end