Description of Covariance
Covariance
PURPOSE
Average covariance of a Gaussian mixture.
SYNOPSIS
function C=Covariance(gm)
DESCRIPTION
   Average covariance of a Gaussian mixture.
   Returns the weighted average of the covariance of the components in the
   input Gaussian mixture.
CROSS-REFERENCE INFORMATION
This function calls:
get Get for GBeliefs.
get Get function for the GMixture object.
get Gaussian object get function.
get Get function for CS_CO_CA_POMDPs.
get Get function for CS_CO_DA_POMDPs.
get Get function for CS_CO_POMDPs.
get Get function for CS_DO_CA_POMDPs.
get Get function for CS_DO_DA_POMDPs.
get Get function for CS_POMDPs.
get Get function for DS_CO_CA_POMDPs.
get Get function for DS_CO_DA_POMDPs.
get Get function for DS_DO_CA_POMDPs.
get Get function for DS_DO_DA_POMDPs.
get Get functio for POMDPs.
This function is called by:
FuseComponents Fuses a Gaussian mixture into a single Gaussian.
SOURCE CODE
function C=Covariance(gm)
%   Average covariance of a Gaussian mixture.
%
%   Returns the weighted average of the covariance of the components in the
%   input Gaussian mixture.
  if gm.n>0
    C=gm.w(1)*get(gm.g{1},'covariance');
    for i=2:gm.n
      C=C+gm.w(i)*get(gm.g{i},'covariance');
    end
  else
    C=0;
  end