Description of FuseComponents
FuseComponents
PURPOSE
Fuses a Gaussian mixture into a single Gaussian.
SYNOPSIS
function g=FuseComponents(gm)
DESCRIPTION
   Fuses a Gaussian mixture into a single Gaussian.
   Summarizes the information on a Gaussian mixture into a single
   Gaussian.
   The mean of the output Gaussian is the weighted mean of the components
   in the input mixture.
   The covariance is basically the weighted mean of the covariance of the
   components but it also take into account the dispersion of the mean of
   the components.
   See also @GMixture/Mean, @GMixture/Covariance, CompressGR.
CROSS-REFERENCE INFORMATION
This function calls:
get Get for GBeliefs.
Covariance Average covariance of a Gaussian mixture.
Mean Mean of a Gmixture.
get Get function for the GMixture object.
Gaussian Gaussian construtor.
get Gaussian object get function.
get Get function for CS_CO_CA_POMDPs.
get Get function for CS_CO_DA_POMDPs.
get Get function for CS_CO_POMDPs.
get Get function for CS_DO_CA_POMDPs.
get Get function for CS_DO_DA_POMDPs.
get Get function for CS_POMDPs.
get Get function for DS_CO_CA_POMDPs.
get Get function for DS_CO_DA_POMDPs.
get Get function for DS_DO_CA_POMDPs.
get Get function for DS_DO_DA_POMDPs.
get Get functio for POMDPs.
This function is called by:
CompressGR Gaussian mixture compression using the Golberger and Roweis method.
SOURCE CODE
function g=FuseComponents(gm)
%   Fuses a Gaussian mixture into a single Gaussian.
%
%   Summarizes the information on a Gaussian mixture into a single
%   Gaussian.
%   The mean of the output Gaussian is the weighted mean of the components
%   in the input mixture.
%   The covariance is basically the weighted mean of the covariance of the
%   components but it also take into account the dispersion of the mean of
%   the components.
%
%   See also @GMixture/Mean, @GMixture/Covariance, CompressGR.
  m=Mean(gm);
  S=Covariance(gm);
  for i=1:gm.n
    v=(get(gm.g{i},'mean')-m);
    S=S+gm.w(i)*(v*v');
  end
  g=Gaussian(m,S);