Description of GMixture
GMixture
PURPOSE
Gaussian mixture constructor.
SYNOPSIS
function gm=GMixture(varargin)
DESCRIPTION
   Gaussian mixture constructor.
   Defines a (non-necessarily normalized) Gaussian mixture given the
   weights and the Gaussian  for each component.
   Possible parameters
     - None: Defines an empty Gaussian mixture.
     - Another Gaussian mixture: Copy constructor.
     - w,g: The (row) vector of weigths and a cell array of Gaussians.
     - g: The cell array of Gaussians. In this case the weights are
          assumed uniform.
CROSS-REFERENCE INFORMATION
This function calls:
size Returns the size of a policy.
GMixture Gaussian mixture constructor.
This function is called by:
GetTest1Parameters The example on Figure 1.
MakeFigure4 Generates Figure 4.
CompressGR Gaussian mixture compression using the Golberger and Roweis method.
Crop Limits all means to be inside the given space.
GMixture Gaussian mixture constructor.
GetFirstComponents Gets the first components of a GMixture.
GetLargestComponents Gets the components with the largest weigth.
GetRandomComponents Selects components at random.
Normalize Normalize a GMixture.
Product gmOut=Product(gm1,gm2)
RemoveSmallComponents Eliminates the small components of a GMixture.
CS_CO_ObsModel CS_CO_ObsModel constructor.
DiscretizeObsModel Discretizes the observation model on the observation side.
GetObsModelFixedO Defines p(o|s) for a fixed 'o'.
GetObsModelFixedS Defines p(o|s) for a fixed 's'.
ComputeAlpha_a Compute the alpha_i_n-element for the given action and belief.
ComputeAlpha_j_a_o Computes a particular alpha-element.
DiscretizeRewardModel Discretizes the reward model on the action side.
GetRewardModelFixedA Defines the reward function for a given action.
UniformDistribution Uniform probability on a continuous space.
SOURCE CODE
function gm=GMixture(varargin)
%   Gaussian mixture constructor.
%
%   Defines a (non-necessarily normalized) Gaussian mixture given the
%   weights and the Gaussian  for each component.
%   Possible parameters
%     - None: Defines an empty Gaussian mixture.
%     - Another Gaussian mixture: Copy constructor.
%     - w,g: The (row) vector of weigths and a cell array of Gaussians.
%     - g: The cell array of Gaussians. In this case the weights are
%          assumed uniform.
  switch nargin
    case 0
      gm.w=[];
      gm.g={};
      gm.n=0;
      gm=class(gm,'GMixture');
    case 1
      if isa(varargin{1},'GMixture')
        gm=varargin{1};
      else
        if isa(varargin{1},'cell')
          n=size(varargin{1},2);
          gm=GMixture(ones(1,n)/n,varargin{1});
        else
          error('Wrong type of parameters in GMixture constructor');
        end
      end
    case 2
      n1=size(varargin{1},2);
      n2=size(varargin{2},2);
      if n1~=n2
        error('Size missmatch in GMixture constructor');
      end
      if isa(varargin{1},'double')
        gm.w=varargin{1};
      else
        error('Wrong type of parameters in GMixture constructor');
      end
      if isa(varargin{2},'cell')
        gm.g=varargin{2};
      else
        error('Wrong type of parameters in GMixture constructor');
      end
      gm.n=n1;
      gm=class(gm,'GMixture');
    otherwise
      error('Wrong number of parameters in GMixture constructor');
  end