Description of Normalize
Normalize
PURPOSE
Normalize a GMixture.
SYNOPSIS
function gmC=Normalize(gm)
DESCRIPTION
   Normalize a GMixture.
   Normalize the weights of a Gaussian mixture. All weights are converted
   to possitive in the range [0,1] and their sum is set to 1.
CROSS-REFERENCE INFORMATION
This function calls:
GMixture Gaussian mixture constructor.
This function is called by:
GBelief Gaussian-based belief constructor.
Compress Gaussian mixutre compression.
CompressGR Gaussian mixture compression using the Golberger and Roweis method.
GetObsModelFixedS Defines p(o|s) for a fixed 's'.
SOURCE CODE
function gmC=Normalize(gm)
%   Normalize a GMixture.
%
%   Normalize the weights of a Gaussian mixture. All weights are converted
%   to possitive in the range [0,1] and their sum is set to 1.
  w=abs(gm.w);
  gmC=GMixture(w/sum(w),gm.g);