Description of Value
Value
PURPOSE
Evaluates a GMixture.
SYNOPSIS
function v=Value(gm,x)
DESCRIPTION
   Evaluates a GMixture.
   Evaluates the Gaussian mixture 'gm' on a given point, 'x'.
CROSS-REFERENCE INFORMATION
This function calls:
Value Evaluates a GMixture.
Value Evaluation of a Gaussian.
This function is called by:
DiscretizeActionModel Produces a new action model discretizing the state space.
DiscretizeActionModel Generates a new action model discretizing the action space of the given model.
GetActionModelFixedA Returns the action model for a given action.
Expectation Expectation between a belief and a alpha-element.
Update Belief evolution under an observation model.
ComponentsValue Evaluates a Gaussian mixture component-wise.
ProductInt Product and marginalization of two GMixtures.
Value Evaluates a GMixture.
plot Plots a Gaussian mixture.
ProductNormFactor Normalization constant of the product of two Gaussians.
plot Plots a Gaussian.
CS_CO_ObsModel CS_CO_ObsModel constructor.
GetObsModelFixedO Defines p(o|s) for a fixed 'o'.
GetObsModelFixedS Defines p(o|s) for a fixed 's'.
plot Plots the CS_CO_ObsModel
CS_DO_ObsModel CS_DO_ObsModel constructor.
DiscretizeObsModel Discretizes the observation model on the state side.
GetObsModelFixedS Defines p(o|s)
GetObsModelFixedO Defines p(s|o).
Perseus The Perseus point-based POMDP solver.
iPerseus Improved version of Perseus.
DiscretizeRewardModel Discretizes the reward model on the action side.
GetRewardModelFixedA Defines the reward function for a given action.
Reward Evaluates the reward function.
plot Plots the CS_CA_RewardModel
DiscretizeRewardModel Discretizes the reward model on the state side.
Reward Evaluates the reward function.
GetRewardModelFixedA Defines the reward function for a given action.
Reward Evaluates the reward function.
UniformDistribution Uniform probability on a continuous space.
SOURCE CODE
function v=Value(gm,x)
%   Evaluates a GMixture.
%
%   Evaluates the Gaussian mixture 'gm' on a given point, 'x'.
  v=0;
  for i=1:gm.n
    v=v+gm.w(i)*Value(gm.g{i},x);
  end