Description of GenerateFigure7aData
GenerateFigure7aData
PURPOSE
Generates the data for Figure 7-left.
SYNOPSIS
function GenerateFigure7aData(fname)
DESCRIPTION
   Generates the data for Figure 7-left.
   In this experiment we compute the time (in seconds) for the first
   iteration of Perseus for a discretized version of the problem
   described in Figure 1 with increasing number of states.
   This gives allow to compare the computational complexity of the discrete
   and the continuous versions of Perseus (compare the execution times
   here with those in Figure 5).
   Parameters:
     fname: file where to store the results.
   See also MakeFigure1, MakeFigure7.
CROSS-REFERENCE INFORMATION
This function calls:
size Returns the size of a policy.
DBelief Discrete belief constructor.
get Get for GBeliefs.
GetTest1Parameters The example on Figure 1.
get Get function for the GMixture object.
get Gaussian object get function.
get Get function for CS_CO_CA_POMDPs.
get Get function for CS_CO_DA_POMDPs.
get Get function for CS_CO_POMDPs.
get Get function for CS_DO_CA_POMDPs.
Discretize Discretizes the state space of the CS_DO_DA_POMDP.
get Get function for CS_DO_DA_POMDPs.
get Get function for CS_POMDPs.
get Get function for DS_CO_CA_POMDPs.
get Get function for DS_CO_DA_POMDPs.
get Get function for DS_DO_CA_POMDPs.
get Get function for DS_DO_DA_POMDPs.
POMDP POMDP constructor.
Perseus The Perseus point-based POMDP solver.
SampleBeliefs Samples a set of beliefs from a POMDP.
UniformDistribution Uniform distribution in the POMDP state space.
get Get functio for POMDPs.
Discretize Converts a continuous space into a discrete one.
UniformDistribution Uniform probability on a continuous space.
UniformDistribution Uniform probability on a discrete space.
This function is called by:
MakeFigure7 Generates Figure 7.
SOURCE CODE
function GenerateFigure7aData(fname)
%   Generates the data for Figure 7-left.
%
%   In this experiment we compute the time (in seconds) for the first
%   iteration of Perseus for a discretized version of the problem
%   described in Figure 1 with increasing number of states.
%   This gives allow to compare the computational complexity of the discrete
%   and the continuous versions of Perseus (compare the execution times
%   here with those in Figure 5).
%
%   Parameters:
%     fname: file where to store the results.
%
%   See also MakeFigure1, MakeFigure7.
   ns=100:100:1000;
   % Nothing to be modified beyond this point
   nns=size(ns,2);
   [POMDP P]=GetTest1Parameters;
   stopCriteria=@(n,t,vc)(n>1);
   nRep=5;
   tp=zeros(1,nns);
   k=1;
   for n=ns
     fprintf('Discretizing the POMDP with %u states\n',n);
     DPOMDP=Discretize(POMDP,n);
     start=DBelief(UniformDistribution(get(DPOMDP,'StateSpace')));
     fprintf('Sampling Beliefs\n');
     B=SampleBeliefs(DPOMDP,start,P.nBeliefs,P.dBelief,P.stepsXtrial,P.rMin,P.rMax);
     r=0;
     for s=1:nRep
       [V Val Alpha t]=Perseus(DPOMDP,B,stopCriteria);
       r=r+t(2);
     end
     tp(k)=r/nRep;
     k=k+1;
   end
   save(fname,'ns','tp');