Description of GetTest1pParameters
GetTest1pParameters
PURPOSE
The example on Figure 8.
SYNOPSIS
function [POMDP P]=GetTest1pParameters(varargin)
DESCRIPTION
   The example on Figure 8.
   This is the same example as GetTest1Parameters but using particles to
   represent beliefs instead of Gaussian mixtures.
   See also GetTest1Parameters.
CROSS-REFERENCE INFORMATION
This function calls:
get Get for GBeliefs.
PBelief Particle-based belief constructor.
GetTest1Parameters The example on Figure 1.
get Get function for the GMixture object.
set Set method for Gaussian mixtures.
get Gaussian object get function.
get Get function for CS_CO_CA_POMDPs.
get Get function for CS_CO_DA_POMDPs.
get Get function for CS_CO_POMDPs.
get Get function for CS_DO_CA_POMDPs.
Discretize Discretizes the state space of the CS_DO_DA_POMDP.
get Get function for CS_DO_DA_POMDPs.
get Get function for CS_POMDPs.
get Get function for DS_CO_CA_POMDPs.
get Get function for DS_CO_DA_POMDPs.
get Get function for DS_DO_CA_POMDPs.
get Get function for DS_DO_DA_POMDPs.
POMDP POMDP constructor.
get Get functio for POMDPs.
set Set function for PODMP (base type)
Discretize Converts a continuous space into a discrete one.
This function is called by:
SOURCE CODE
function [POMDP P]=GetTest1pParameters(varargin)
%   The example on Figure 8.
%
%   This is the same example as GetTest1Parameters but using particles to
%   represent beliefs instead of Gaussian mixtures.
%
%   See also GetTest1Parameters.
   % Test1 with the default paramters
   %   ncBelief = 4 (not used)
   %   ncAlpha = 9
   %   actionScale = 2
   [POMDP P]=GetTest1Parameters();
   set(POMDP,'name','Test1p');
   if nargin==0
     npBelief=25;
   else
     npBelief=varargin{1};
   end
   S=get(POMDP,'StateSpace');
   [DS samples]=Discretize(S,npBelief);
   P.start=PBelief(ones(1,npBelief),samples);