Description of MakeFigure11
MakeFigure11
PURPOSE
Generates Figure 11.
SYNOPSIS
function MakeFigure11
DESCRIPTION
  Generates Figure 11.
   Generates the data for Figure 11 in the paper.
   In this figure we show the performance of planning in the example in
   Figure 1 when using a continuous action and observation sets.
   This simulation takes longer that those in the paper because in this
   implementation focus is on clarity and not on efficiency.
   See also MakeFigure2, MakeFigure 11, GetData, TestRep,
            GetPOMDPAverageStatistics,
            TestRepWithStatistics, MakeFigureSimulation.
CROSS-REFERENCE INFORMATION
This function calls:
MakeFigureSimulation Generates the plots in Figures 2, 8, 10, and 11.
GetData Loads and, if necessary, generates data from experiments.
TestRepWithStatistics Executes many times Perseus on a given problem and collects statistics.
This function is called by:
SOURCE CODE
function MakeFigure11
%  Generates Figure 11.
%
%   Generates the data for Figure 11 in the paper.
%   In this figure we show the performance of planning in the example in
%   Figure 1 when using a continuous action and observation sets.
%
%   This simulation takes longer that those in the paper because in this
%   implementation focus is on clarity and not on efficiency.
%
%   See also MakeFigure2, MakeFigure 11, GetData, TestRep,
%            GetPOMDPAverageStatistics,
%            TestRepWithStatistics, MakeFigureSimulation.
   fprintf('Loading/Generating the simulation results\n');
   GenData=@()(TestRepWithStatistics('Test1co','Figure11',1:10));
   Results=GetData('Results/Test1co-Figure11-results.mat',GenData);
   MakeFigureSimulation('C-POMDP Figure 11',Results);