Description of MakeFigure1
MakeFigure1
PURPOSE
Generates Figure 1.
SYNOPSIS
function MakeFigure1
DESCRIPTION
   Generates Figure 1.
   Displays the two lower plots of Figure 1 in the paper (i.e., the
   observation model and the reward model).
   This is an example of how to get and manipulate observation and reward
   models.
   See also GetTest1Parameters.
CROSS-REFERENCE INFORMATION
This function calls:
plot Plots a discrete belief.
get Get for GBeliefs.
plot Displays a particle-based belief.
GetTest1Parameters The example on Figure 1.
get Get function for the GMixture object.
plot Plots a Gaussian mixture.
set Set method for Gaussian mixtures.
get Gaussian object get function.
plot Plots a Gaussian.
GetObsModelFixedO Defines p(o|s) for a fixed 'o'.
plot Plots the CS_CO_ObsModel
GetObsModelFixedO Defines p(o|s) for a fixed 'o'.
GetObsModelFixedO Defines p(s|o).
GetObsModelFixedO Defines p(s|o).
get Get function for CS_CO_CA_POMDPs.
get Get function for CS_CO_DA_POMDPs.
get Get function for CS_CO_POMDPs.
get Get function for CS_DO_CA_POMDPs.
get Get function for CS_DO_DA_POMDPs.
get Get function for CS_POMDPs.
get Get function for DS_CO_CA_POMDPs.
get Get function for DS_CO_DA_POMDPs.
get Get function for DS_DO_CA_POMDPs.
get Get function for DS_DO_DA_POMDPs.
POMDP POMDP constructor.
get Get functio for POMDPs.
set Set function for PODMP (base type)
GetRewardModelFixedA Defines the reward function for a given action.
plot Plots the CS_CA_RewardModel
GetRewardModelFixedA Defines the reward function for a given action.
GetRewardModelFixedA Defines the reward function for a given action.
GetRewardModelFixedA Defines the reward function for a given action.
This function is called by:
SOURCE CODE
function MakeFigure1
%   Generates Figure 1.
%
%   Displays the two lower plots of Figure 1 in the paper (i.e., the
%   observation model and the reward model).
%
%   This is an example of how to get and manipulate observation and reward
%   models.
%
%   See also GetTest1Parameters.
  [POMDP P]=GetTest1Parameters;
  h=clf;
  set(h,'name','C-POMDP Figure 1','numbertitle','off');
  subplot(2,1,1);
  OM=get(POMDP,'ObsModel');
  plot(GetObsModelFixedO(OM,1),'color','k','linestyle',':');
  plot(GetObsModelFixedO(OM,2),'color','k','linestyle','-.');
  plot(GetObsModelFixedO(OM,4),'color','k');
  plot(GetObsModelFixedO(OM,3),'color','k','linestyle','--');
  legend('Left End','Right End','Corridor','Door');
  axis([-20 20 0 1.1]);
  title('Observation Model');
  xlabel('s');
  ylabel('p(o)');
  subplot(2,1,2);
  RM=get(POMDP,'RewardModel');
  plot(GetRewardModelFixedA(RM,1),'color','k','linestyle',':');
  plot(GetRewardModelFixedA(RM,2),'color','k','linestyle','-.');
  plot(GetRewardModelFixedA(RM,3),'color','k');
  legend('Move Left','Move Right','Enter Door');
  axis([-20 20 -1.2 0.4]);
  xlabel('s');
  ylabel('r(a)');
  title('Reward Model');