Description of GetActionModelFixedA
GetActionModelFixedA
PURPOSE
Returns the action model for a given action.
SYNOPSIS
function p=GetActionModelFixedA(AM,a)
DESCRIPTION
   Returns the action model for a given action.
   Returns the action model when the action is is fixed to 'a'.
   The output is a Gaussian with the mean and covariance given in the
   CS_DA_ActionModel constructor.
   See also CS_DA_ActionModel.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
BeliefPrediction Belief evolution under a given action.
ComputeAlpha_j_a_o Computes a particular alpha-element.
ComputeAlpha_j_a_o Computes a particular alpha-element.
SOURCE CODE
function p=GetActionModelFixedA(AM,a)
%   Returns the action model for a given action.
%
%   Returns the action model when the action is is fixed to 'a'.
%   The output is a Gaussian with the mean and covariance given in the
%   CS_DA_ActionModel constructor.
%
%   See also CS_DA_ActionModel.
  % Gaussian in the displacement
  p=AM.gA{a};